# https://github.com/marketplace/actions/rust-release-binary

name: Release binary

on:
  release:
    types: [created]

jobs:
  build-artifacts:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v3
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: ./cli

  boilerplate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Zip & Upload
        run: |
          tar -zcvf boilerplate.tar.gz ./boilerplate
          gh release upload $GITHUB_REF boilerplate.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
